APP_TITLE = "IMC Prosperity Dashboard"

BACKTESTER_INSTALL_HINT = "pip install -U prosperity4btest"
DEFAULT_BACKTEST_PRESET = "tutorial_round_0"
DEFAULT_MATCH_TRADES = "all"
DEFAULT_LIMIT_OVERRIDES_TEXT = "EMERALDS:80\nTOMATOES:80"
ROUND_0_LIMITS = {"EMERALDS": 80, "TOMATOES": 80}
BACKTEST_DAY_SCAN_RANGE = list(range(-10, 11))
