APP_TITLE = "IMC Prosperity Dashboard"

BACKTESTER_INSTALL_HINT = "pip install -U prosperity4btest"
DEFAULT_MATCH_TRADES = "all"
ROUND_0_LIMITS = {"EMERALDS": 80, "TOMATOES": 80}
BACKTEST_DAY_SCAN_RANGE = list(range(-10, 11))
DEFAULT_BACKTEST_PRESET = "selected_dashboard_round"
DEFAULT_LIMIT_OVERRIDES_TEXT = "ASH_COATED_OSMIUM:80\nINTARIAN_PEPPER_ROOT:80"