from __future__ import annotations

import os

APP_TITLE = "IMC Prosperity Dashboard"

BACKTESTER_INSTALL_HINT = "cargo install rust_backtester --locked"
RUST_BACKTESTER_BIN = os.getenv("RUST_BACKTESTER_BIN", "rust_backtester")
RUST_BACKTESTER_ARTIFACT_MODE = os.getenv("RUST_BACKTESTER_ARTIFACT_MODE", "submission")
RUST_BACKTESTER_PRODUCTS_MODE = os.getenv("RUST_BACKTESTER_PRODUCTS_MODE", "summary")
DEFAULT_MATCH_TRADES = "all"
ROUND_0_LIMITS = {"EMERALDS": 80, "TOMATOES": 80}
BACKTEST_DAY_SCAN_RANGE = list(range(-10, 11))
DEFAULT_BACKTEST_PRESET = "selected_dashboard_round"
DEFAULT_LIMIT_OVERRIDES_TEXT = "ASH_COATED_OSMIUM:80\nINTARIAN_PEPPER_ROOT:80"
BACKTEST_ACTIVITY_PARSE_MAX_ROWS = int(os.getenv("BACKTEST_ACTIVITY_PARSE_MAX_ROWS", "120000"))
